"""empty message

Revision ID: 1a4e7ead6ec6
Revises: 3fce84ad96d3
Create Date: 2015-04-10 15:15:25.165395

"""

# revision identifiers, used by Alembic.
revision = '1a4e7ead6ec6'
down_revision = '3fce84ad96d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
