"""empty message

Revision ID: e1dbf7e99ff
Revises: 374a385e9080
Create Date: 2015-04-10 19:04:06.446369

"""

# revision identifiers, used by Alembic.
revision = 'e1dbf7e99ff'
down_revision = '374a385e9080'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
