"""empty message

Revision ID: 1fea5f20dda8
Revises: None
Create Date: 2015-04-27 17:23:58.022414

"""

# revision identifiers, used by Alembic.
revision = '1fea5f20dda8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'player', ['submitted_by'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'submitted_by')
    ### end Alembic commands ###
