"""empty message

Revision ID: 3fce84ad96d3
Revises: 4740002021a7
Create Date: 2015-04-06 15:43:14.381334

"""

# revision identifiers, used by Alembic.
revision = '3fce84ad96d3'
down_revision = '4740002021a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('nick_name', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=120), nullable=False),
    sa.Column('skill', sa.Float(), nullable=True),
    sa.Column('skill_sd', sa.Float(), nullable=True),
    sa.Column('office', sa.Enum('Brighton', 'New York', 'Berlin', 'San Francisco', 'Stuttgart', 'London'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'email')
    )
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('api_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_user_id'), 'api_user', ['id'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('loser_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('skill', sa.Float(), nullable=True),
    sa.Column('skill_sd', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('participant',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    op.drop_table('skill_history')
    op.drop_table('game')
    op.drop_index(op.f('ix_api_user_id'), table_name='api_user')
    op.drop_table('api_user')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_table('player')
    ### end Alembic commands ###
