"""empty message

Revision ID: 4740002021a7
Revises: 5027b5051fda
Create Date: 2015-04-05 16:28:14.335045

"""

# revision identifiers, used by Alembic.
revision = '4740002021a7'
down_revision = '5027b5051fda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_user_id'), 'api_user', ['id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_user_id'), table_name='api_user')
    op.drop_table('api_user')
    ### end Alembic commands ###
